### ISSUE TITLE
欢太改成OPPO商城了，脚本失效了

### ISSUE THREAD

**Issue by cisco6005** [Mashiro2000/QL_HeyTap#154]
## 开始执行... 2022-01-04 05:25:01

鉴于青龙面板会破坏欢太CK格式，尝试修复无效，故建议使用配置文件
该项目不再支持青龙面板`环境变量`添加账号,请将CK转移至配置文件
青龙面板 -> 脚本管理 -> 搜索`HT_account`关键字 -> 编辑
CK最简格式:'source_type=xxx;TOKENSID=xxx;app_param=xxx;'

任务:欢太任务中心
时间:2022-01-04 05:25:04
cisco6005	登录成功
cisco6005	失败原因:authenticate token fail
****************************************

账号:空账户	状态:跳过
****************************************

企业微信机器人服务启动
企业微信机器人 推送成功！

## 执行结束... 2022-01-04 05:25:08 耗时 7 秒

**Comment by Wittoy** [comment]
#132
