### ISSUE TITLE
任务领取金币验证改为旋转验证了希望作者大佬可以修复下脚本

### ISSUE THREAD

**Issue by MagnusWTC** [Mashiro2000/QL_HeyTap#157]
任务:欢太任务中心
时间:2022-03-10 09:37:53
Magnus	登录成功
Magnus	今日已签到
浏览商品	领取失败
分享商品到微信	领取失败
Magnus	总积分:2003

**Comment by Mashiro2000** [comment]
验证码问题，未研究过，主学其他方面
