### ISSUE TITLE
大佬，oppo商城目前已经删除验证码了，可以正常了，还有兴趣继续维护吗

### ISSUE THREAD

**Issue by zhangwenwu** [Mashiro2000/QL_HeyTap#159]
OPPO 积分签到及任务，，，现存OPPO积分主要以视频-OPPO商城-y鸭梦想家积分最高，，视频每日固定100-200积分，OPPO商城50积分上下看运气（因为是抽奖），鸭子就靠自己喂了（50个蛋值1000积分，记得每天领取沙漠背景神灯的双倍卡以及任务饲料），，目前每天一个账号积分在300-400左右，也就是一个月9000-12000积分左右

**Comment by Mashiro2000** [comment]
有其他计划，时间安排不是很充分，暂时不考虑

**Comment by zhangwenwu** [comment]
dddd
