### ISSUE TITLE
现在还更新吗？

### ISSUE THREAD

**Issue by qqhbc5918** [Mashiro2000/QL_HeyTap#161]

**Comment by jjustwin** [comment]
现在好像只有一个任务能正常运行

**Comment by qqhbc5918** [comment]
好吧，那就挂这个没有意义了，如果有其他项目，会跟着挂的，谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jjustwin ***@***.***&gt;
发送时间: 2022年5月26日 09:27
收件人: Mashiro2000/HeyTapTask ***@***.***&gt;
抄送: qqhbc5918 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Mashiro2000/HeyTapTask] 现在还更新吗？ (Issue #161)
