### ISSUE TITLE
多账户可以么

### ISSUE THREAD

**Issue by 166679551** [Mashiro2000/QL_HeyTap#3]
如题

**Comment by Mashiro2000** [comment]
可以

**Comment by 166679551** [comment]
> 可以
我开两个变量只跑一个

**Comment by Mashiro2000** [comment]
四个参数都需要填写
user，ua，ck，app_prams
我自己跑三个没问题啊

**Comment by donaldrobert** [comment]
怎么获取ck啊我这边一直只看到source_type!求求大佬顺手给个教程

**Comment by 166679551** [comment]
> 四个参数都需要填写
> user，ua，ck，app_params
> 我自己跑三个没问题啊

谢谢回复是我变量写错了已经可以了

**Comment by donaldrobert** [comment]
求帮忙给个提CK的教程谢谢

**Comment by donaldrobert** [comment]
我的QQ2818576493,把你们的qq给我也行

**Comment by Mashiro2000** [comment]
> 我的QQ2818576493,把你们的qq给我也行
欢太商城 -> 我的 -> 任务中心 -> 领券中心
抓包地址:https://store.oppo.com/cn/oapi/users/web/checkPeople/isNewPeople
其中app_param包含在CK中，由于青龙面板把嵌套JSON转换为不可直接转变的字符串,需手动提取'app_param'
