### ISSUE TITLE
登陆问题

### ISSUE THREAD

**Issue by WinverLemon** [Mashiro2000/QL_HeyTap#45]
我认为我的COOKIE没问题 脚本不运行  上一版可以正常运行的

**Comment by laoxiu001** [comment]
+1

**Comment by Mashiro2000** [comment]
你们有把CK放到HT_account.py里面吗

**Comment by laoxiu001** [comment]
> 你们有把CK放到HT_account.py里面吗
感谢回复，检查后发现是HT_account.py文件格式出错了，但是都没去动过，可能是青龙的锅吧？
![image](https://user-images.githubusercontent.com/20652480/136693961-c75a74e3-4bfb-4667-8438-ed586c494a18.png)

**Comment by WinverLemon** [comment]
@Mashiro2000 老哥可以给个邮箱吗，我发给你ck，你给看一下

**Comment by Mashiro2000** [comment]
> @Mashiro2000 老哥可以给个邮箱吗，我发给你ck，你给看一下

463022229@qq.com
