### ISSUE TITLE
大佬,本地ck和环境变量还没更新好

### ISSUE THREAD

**Issue by shenmadouyaowen** [Mashiro2000/QL_HeyTap#5]
![image](https://user-images.githubusercontent.com/12426724/134268119-38155195-7906-4dd3-92b8-e6a4e82edd2a.png)

**Comment by Mashiro2000** [comment]
建议使用HT_config.py这个配置文件，青龙面板会错误解析CK和UA
青龙变量添加CK的方案后续会删除，代码没问题，文档删除了青龙面板CK格式

**Comment by Mashiro2000** [comment]
青龙环境变量的格式，包含四个参数`user`、`CK`、`UA`、`app_param`
```text
{
    'user':'',                                                  # 自定义备注(为了区分账号，包括未登录状态下)
    'CK':'source_type=501;TOKENSID=TOKEN_xxxx;',  # 用户环境变量 Cookie,建议全部粘贴
    'UA':'UA',                                                   # 用户环境变量 User-Agent
    'app_param':'{"a":"a","b":"b"}'
}
```

**Comment by shenmadouyaowen** [comment]
是的,我填本地变量,然后把青龙变量删除,就运行不了

**Comment by shenmadouyaowen** [comment]
但是我填了本地ck文件和环境ck变量就运行了两次,删除本地变量可以运行,删除环境变量无法运行,我看了一下代码,运行需要环境变量才能往下操作

**Comment by shenmadouyaowen** [comment]
大佬,是我错了,青龙变量禁用不代表删除,
