### ISSUE TITLE
今天任务登陆显示异常

### ISSUE THREAD

**Issue by dark748001** [Mashiro2000/QL_HeyTap#55]
![image](https://user-images.githubusercontent.com/64937100/137657256-b998629a-7904-4f1e-a683-d52663acc166.png)
![image](https://user-images.githubusercontent.com/64937100/137657267-20c20238-54e5-460b-84c4-c318ff6e72dd.png)

**Comment by dark748001** [comment]
![image](https://user-images.githubusercontent.com/64937100/137657714-faa205ee-9b53-45ef-8086-bdb4a23c3555.png)

**Comment by gdw1986** [comment]
看来不是我的ck的问题

**Comment by dark748001** [comment]
我是一直跑着的 就是今天出的问题
